r"""Build a single self-contained comparison file: kb-compare.html

Inlines the Tailwind CSS actually needed by the three variants (_tw.out.css,
generated by the tailwindcss CLI) and the post-React DOM of each variant
(_snapshots.json, captured by _snapshot.py). The result opens by double-click
with no server, no CDN and no network.

Regenerate the inputs first:
    node build.js
    npx tailwindcss@3.4.17 -i _tw.css -o _tw.out.css \
        --content "./_orig.tsx,./_base.tsx,./_senior.tsx" --minify
    python _snapshot.py          # needs the compare/ server on :3002
    python make_standalone.py
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
# generated inputs and the finished bundle live in the ignored output tree
ART = os.path.join(ROOT, "outputs", "compare")
VIEWER = os.path.join(ROOT, "tools", "viewers", "kb_compare.html")
CSS = open(os.path.join(ART, "_tw.out.css"), encoding="utf-8").read()
SNAP = json.load(open(os.path.join(ART, "_snapshots.json"), encoding="utf-8"))

SHELL = open(VIEWER, encoding="utf-8").read()

# The shell's <style> and <header>/<main>/<table> markup are reused verbatim;
# only the frame-loading part differs, so cut the shell at its <script>.
head, _sep, _tail = SHELL.partition("<script>")
head = head.replace('<html lang="ko">', '<html lang="ko">')

JS = """
var CSS = %(css)s;
var SNAP = %(snap)s;
var VARIANTS = [
  {id:'orig',   label:'Original',  sub:'DesignRepair/examples/example1.tsx', tag:''},
  {id:'base',   label:'Base KB',   sub:'outputs/example1_base/property_example1.tsx',
   tag:'<span class="tag w">제안 12 · 규칙 ID 0</span>'},
  {id:'senior', label:'Senior KB', sub:'outputs/example1_seniorkb/property_example1.tsx',
   tag:'<span class="tag g">제안 17 · SDF 인용 12</span>'}
];
var HEIGHT = 1500;
var heights = {};
var width = 1280, fit = true;
var shown = {orig:true, base:true, senior:true};
var grid = document.getElementById('grid');

function doc(id){
  return '<!doctype html><html><head><meta charset="utf-8">' +
         '<style>' + CSS + '</style></head>' +
         '<body style="margin:0"><div id="root">' + SNAP[id] + '</div></body></html>';
}

grid.innerHTML = VARIANTS.map(function(v){
  return '<section class="col" id="col-' + v.id + '">' +
    '<div class="cap"><b>' + v.label + '</b>' + v.tag +
      '<div class="sub">' + v.sub + '</div></div>' +
    '<div class="stage" id="stage-' + v.id + '">' +
      '<iframe id="fr-' + v.id + '" width="' + width + '" height="' + HEIGHT + '"></iframe>' +
    '</div></section>';
}).join('');
VARIANTS.forEach(function(v){ document.getElementById('fr-' + v.id).srcdoc = doc(v.id); });

function measure(v){
  try{
    var d = document.getElementById('fr-' + v.id).contentDocument;
    var root = d && d.getElementById('root');
    var h = root ? Math.ceil(root.getBoundingClientRect().height) : 0;
    if (h > 100) heights[v.id] = h;
  }catch(e){}
}
function layout(){
  var n = VARIANTS.filter(function(v){ return shown[v.id]; }).length || 1;
  grid.style.gridTemplateColumns = 'repeat(' + n + ', minmax(0,1fr))';
  VARIANTS.forEach(function(v){
    var col = document.getElementById('col-' + v.id);
    col.classList.toggle('hidden', !shown[v.id]);
    if (!shown[v.id]) return;
    var fr = document.getElementById('fr-' + v.id);
    var stage = document.getElementById('stage-' + v.id);
    fr.width = width;
    fr.height = heights[v.id] || HEIGHT;
    measure(v);
    fr.height = heights[v.id] || HEIGHT;
    var avail = col.clientWidth;
    var scale = fit ? Math.min(1, avail / width) : 1;
    fr.style.transform = 'scale(' + scale + ')';
    stage.style.height = ((heights[v.id] || HEIGHT) * scale) + 'px';
    stage.style.overflowX = (scale === 1 && width > avail) ? 'auto' : 'hidden';
  });
}
[200, 600, 1500].forEach(function(t){ setTimeout(layout, t); });
function group(sel, fn){
  var els = document.querySelectorAll(sel);
  Array.prototype.forEach.call(els, function(b){
    b.onclick = function(){ fn(b, els); layout(); };
  });
}
group('[data-w]', function(b, els){
  width = +b.dataset.w;
  Array.prototype.forEach.call(els, function(o){ o.setAttribute('aria-pressed', o === b); });
});
group('[data-fit]', function(b, els){
  fit = b.dataset.fit === '1';
  Array.prototype.forEach.call(els, function(o){ o.setAttribute('aria-pressed', o === b); });
});
group('[data-col]', function(b){
  var id = b.dataset.col;
  shown[id] = !shown[id];
  b.setAttribute('aria-pressed', shown[id]);
});
addEventListener('resize', layout);
addEventListener('load', layout);
layout();
""" % {"css": json.dumps(CSS), "snap": json.dumps(SNAP, ensure_ascii=False)}

# Context block so a reader picking up only this file knows how it was produced.
CONTEXT = """
<section class="ctx">
  <h2>이 파일은 무엇인가</h2>
  <p>
    DesignRepair 파이프라인을 같은 입력(<code>example1.tsx</code>, <code>http://localhost:3000</code>)으로
    두 번 돌리고, property stream이 낸 결과를 나란히 렌더링한 것입니다.
    차이는 system-level 지식베이스 하나뿐입니다.
  </p>
  <ul>
    <li><b>Base KB</b> — 업스트림 <code>system_design_knowledge_base.csv</code> (Material Design 기반)</li>
    <li><b>Senior KB</b> — 교체한 <code>kb/senior_kb.csv</code>, 46행 (고령자 사용성 지침).
        relation 컬럼이 <code>SDF-G1-1</code> 형태의 규칙 ID라 제안 → 규칙 역추적이 됩니다.</li>
  </ul>
  <h2>실행 결과 요약 (senior_kb.csv)</h2>
  <ul>
    <li>exit 0, Traceback 없음. <code>RateLimitError</code> 1회 → 백오프 후 성공.</li>
    <li>KB 로드 46행 — Group 17 / Text 11 / Clickable 8 / Label 4 / Color 3 / Spacing 2 / Icon 1. 버려진 행 없음.</li>
    <li>실행된 property 5개: Group, Spacing, Text, Color, Icon.
        <b>Label(4규칙) · Clickable(8규칙)은 스킵</b> — 이 페이지에 버튼/링크/폼이 없어
        Playwright 추출이 0입니다. KB 46행 중 12행(26%)은 이 예제에서는 프롬프트에 실리지 않습니다.</li>
    <li>제안 17건 중 12건이 SDF-* 인용 (base는 12건 중 0건).
        distinct 규칙은 7개 — Text 4건은 전부 SDF-G1-1, Color 3건은 전부 SDF-G1-3으로 중복됩니다.</li>
    <li>KS-* 규칙(43~47행, 5개)은 한 건도 인용되지 않았습니다.</li>
  </ul>
  <h2>남은 문제 3가지</h2>
  <ol>
    <li><b>Icon 제안 5건이 규칙 ID를 누락</b> — KB 27행 relation은 <code>SDF-G6-4</code>로 정상인데
        모델이 content 본문만 인용했습니다. 내용은 맞고 인용 포맷만 깨졌습니다.</li>
    <li><b>아이콘 레이블이 h2와 중복</b> — SDF-G6-4를 그대로 적용해
        <code>&lt;span&gt;Smart Inbox&lt;/span&gt;</code>이 <code>&lt;h2&gt;Smart Inbox&lt;/h2&gt;</code> 위에 생겼습니다.</li>
    <li><b>그 span에 색 클래스가 없어 검정으로 렌더링</b> — <code>bg-gray-900</code> 위에 얹혀
        거의 안 보입니다. 명도 대비를 요구하는 SDF-G1-3과 정면으로 충돌합니다.
        Senior 패널 아이콘 오른쪽을 보시면 확인됩니다.</li>
  </ol>
  <h2>배경</h2>
  <p>
    <code>bg-primary</code> / <code>text-primary</code>는 Tailwind에 없는 클래스라
    Base KB 패널은 실제로 저렇게 렌더링됩니다. 렌더 버그가 아니라
    Material 토큰 이름을 클래스명으로 쓴 결과입니다.
  </p>
</section>
"""

CTX_CSS = """
<style>
  .ctx{margin:24px 16px 60px;max-width:1100px;border-top:1px solid var(--line);padding-top:20px}
  .ctx h2{font-size:13px;color:var(--accent);margin:20px 0 8px;font-weight:600}
  .ctx p,.ctx li{color:var(--dim);font-size:12.5px;max-width:900px}
  .ctx ul,.ctx ol{margin:6px 0;padding-left:20px}
  .ctx li{margin:4px 0}
  .ctx b{color:var(--fg)}
  .ctx code{background:#222733;padding:1px 5px;border-radius:4px;
            font-family:ui-monospace,Consolas,monospace;color:#cbd3e3;font-size:11.5px}
</style>
"""

# `head` is everything before the shell's <script>, so it carries no closing
# tags — append them rather than replacing.
out = head.replace("</head>", CTX_CSS + "</head>")
out = out + CONTEXT + "<script>" + JS + "</script>\n</body></html>\n"
out = out.replace(
    "<title>DesignRepair KB 비교 — example1.tsx</title>",
    "<title>DesignRepair KB 비교 — example1.tsx (standalone)</title>")

dest = os.path.join(ART, "kb-compare.html")
with open(dest, "w", encoding="utf-8") as f:
    f.write(out)
print("wrote %s (%.0f KB)" % (dest, os.path.getsize(dest) / 1024))
